services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:admin123@db:5432/citizen_ai
      - AI_DUPLICATE_URL=http://ai-duplicate:9001
      - AI_LLM_URL=http://ai-llm:9002
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
      - ai-duplicate
      - ai-llm

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"

  ai-duplicate:
    build: ./ai-duplicate
    container_name: ai-duplicate
    ports:
      - "9001:9001"

  ai-llm:
    build: ./ai-llm
    container_name: ai-llm
    ports:
      - "9002:9002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  db:
    image: postgis/postgis:15-3.4 # Official PostGIS image
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=citizen_ai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
